# Generated by Django 3.1.4 on 2021-01-02 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='added_data',
            new_name='added_date',
        ),
    ]
